const fs = require('fs')
const path = require('path')
const { execSync, execFileSync } = require('child_process')

// Improved environment variable loader with better error handling and variable substitution
function loadEnvLocal(envPath = '.env.local') {
  try {
    if (!fs.existsSync(envPath)) {
      console.warn(`Environment file ${envPath} not found`)
      return
    }

    const envContent = fs.readFileSync(envPath, 'utf8')
    let loadedCount = 0
    const envVars = {}

    // First pass: load all variables
    envContent.split('\n').forEach((line, index) => {
      const trimmedLine = line.trim()
      if (!trimmedLine || trimmedLine.startsWith('#')) return

      const match = trimmedLine.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/)
      if (match) {
        const key = match[1]
        let value = match[2].replace(/(^['"]|['"]$)/g, '')
        envVars[key] = value
      } else if (trimmedLine) {
        console.warn(`Invalid line ${index + 1} in ${envPath}: ${line}`)
      }
    })

    // Second pass: resolve variable substitutions and set environment variables
    Object.entries(envVars).forEach(([key, value]) => {
      // Handle variable substitution like ${VAR_NAME}
      let resolvedValue = value
      const variablePattern = /\$\{([^}]+)\}/g
      let match

      while ((match = variablePattern.exec(value)) !== null) {
        const varName = match[1]
        const varValue = process.env[varName] || envVars[varName] || ''
        resolvedValue = resolvedValue.replace(match[0], varValue)
      }

      if (!process.env[key]) {
        process.env[key] = resolvedValue
        loadedCount++
        console.log(`Loaded ${key}=${resolvedValue}`)
      }
    })

    console.log(`Loaded ${loadedCount} environment variables from ${envPath}`)
  } catch (error) {
    console.error(`Error loading ${envPath}:`, error.message)
  }
}

// Validate URL format
function isValidUrl(string) {
  try {
    new URL(string)
    return true
  } catch {
    return false
  }
}

// Load environment variables if missing
const requiredVars = [
  'ARTIFACTORY_DOMAIN',
  'ARTIFACTORY_TOKEN',
  'ARTIFACTORY_USERNAME',
  'DESYRE_PROJECT_ID',
  'HTTP_PROXY',
  'HTTPS_PROXY'
]

const missingVars = requiredVars.filter(varName => !process.env[varName])
if (missingVars.length > 0) {
  loadEnvLocal()
}

// Extract and validate environment variables
const {
  ARTIFACTORY_USERNAME,
  ARTIFACTORY_TOKEN,
  DESYRE_PROJECT_ID,
  ARTIFACTORY_DOMAIN,
  HTTP_PROXY,
  HTTPS_PROXY
} = process.env

// Enhanced validation
const stillMissingVars = requiredVars.filter(varName => !process.env[varName])
if (stillMissingVars.length > 0) {
  console.error(
    `Missing required environment variables: ${stillMissingVars.join(', ')}`
  )
  console.error('Set them in your environment or create a .env.local file')
  process.exit(1)
}

// Validate proxy URLs
// if (!isValidUrl(HTTP_PROXY)) {
//   console.error(`Invalid HTTP_PROXY URL: ${HTTP_PROXY}`)
//   process.exit(1)
// }

if (!isValidUrl(HTTPS_PROXY)) {
  console.error(`Invalid HTTPS_PROXY URL: ${HTTPS_PROXY}`)
  process.exit(1)
}

// Create .npmrc with proper error handling
function createNpmrcConfig() {
  const registryUrl = `https://${ARTIFACTORY_DOMAIN}/artifactory/api/npm/${DESYRE_PROJECT_ID}/`
  const npmrcPath = '.npmrc'

  try {
    // Backup existing .npmrc if it exists
    if (fs.existsSync(npmrcPath)) {
      const backupPath = `${npmrcPath}.backup.${Date.now()}`
      fs.copyFileSync(npmrcPath, backupPath)
      console.log(`Backed up existing .npmrc to ${backupPath}`)
    }

    const npmrcContent =
      [
        `registry=${registryUrl}`,
        `http-proxy=${HTTPS_PROXY}`,
        `https-proxy=${HTTPS_PROXY}`,
        `# Generated by setup-desyre-artifactory.js on ${new Date().toISOString()}`
      ].join('\n') + '\n'

    fs.writeFileSync(npmrcPath, npmrcContent)
    console.log(`Created ${npmrcPath} with registry: ${registryUrl}`)
  } catch (error) {
    console.error(`Error creating ${npmrcPath}:`, error.message)
    process.exit(1)
  }
}

// Fetch authentication with better error handling and retry logic
async function fetchAuthWithRetry(maxRetries = 3) {
  const authUrl = `https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_TOKEN}@${ARTIFACTORY_DOMAIN}/artifactory/api/npm/auth`

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(
        `Fetching authentication data (attempt ${attempt}/${maxRetries})...`
      )

      const authData = execFileSync(
        'curl',
        [
          '--proxy',
           HTTPS_PROXY,
          '--silent',
          '--show-error',
          '--fail', // Fail on HTTP error codes
          '--max-time',
          '30', // 30 second timeout
          authUrl
        ],
        {
          encoding: 'utf8',
          timeout: 35000 // 35 second timeout for the process
        }
      )

      if (!authData.trim()) {
        throw new Error('Empty authentication response')
      }

      fs.appendFileSync('.npmrc', authData)
      console.log('Successfully added authentication to .npmrc')
      return
    } catch (error) {
      console.warn(`Attempt ${attempt} failed:`, error.message)

      if (attempt === maxRetries) {
        console.error('Failed to fetch authentication after all retries')
        console.error('Please check your credentials and network connection')
        process.exit(1)
      }

      // Wait before retry (exponential backoff)
      const delay = Math.pow(2, attempt) * 1000
      console.log(`Waiting ${delay}ms before retry...`)
      await new Promise(resolve => setTimeout(resolve, delay))
    }
  }
}

// Main execution with better structure
async function main() {
  try {
    console.log('Setting up Artifactory configuration...')

    createNpmrcConfig()
    await fetchAuthWithRetry()

    console.log('Running npm config fix...')
    execSync('npm config fix', { stdio: 'inherit' })

    console.log('✅ Artifactory setup completed successfully!')
  } catch (error) {
    console.error('❌ Setup failed:', error.message)
    process.exit(1)
  }
}

// Run the script
main()
